name: Node.js Package

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - run: npm test

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.npm_token }}
      - if: steps.publish.outputs.type != 'none'
        name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: ./dist
          target-folder: ${{ steps.publish.outputs.version }}
